resources:
  repositories:
    - repository: templatesRepo
      type: github
      name: rathoddt/Azure-DevOps
      ref: main
      endpoint: rathoddt

steps:
  - template: Azure-Pipelines/templates/template.yaml@templatesRepo



